
export const displayNames = {
	'$mat_acid': 'acid' as const,
	'$mat_acid_gas': 'flammable gas' as const,
	'$mat_acid_gas_static': 'flammable gas' as const,
	'$mat_air': 'air' as const,
	'$mat_alcohol': 'whiskey' as const,
	'$mat_aluminium': 'aluminium' as const,
	'$mat_aluminium_molten': 'molten aluminium' as const,
	'$mat_aluminium_oxide': 'aluminium' as const,
	'$mat_aluminium_oxide_molten': 'molten aluminium' as const,
	'$mat_aluminium_robot_molten': 'molten aluminium' as const,
	'$mat_blood': 'blood' as const,
	'$mat_blood_cold': 'freezing liquid' as const,
	'$mat_blood_cold_vapour': 'freezing vapour' as const,
	'$mat_blood_fading': 'blood' as const,
	'$mat_blood_fading_slow': 'fungal blood' as const,
	'$mat_blood_fungi': 'fungus' as const,
	'$mat_blood_thick': 'blood' as const,
	'$mat_blood_worm': 'worm blood' as const,
	'$mat_bluefungi_static': 'blue fungus' as const,
	'$mat_bone': 'bone dust' as const,
	'$mat_bone_box2d': 'bone' as const,
	'$mat_bone_static': 'bone wall' as const,
	'$mat_brass': 'brass' as const,
	'$mat_brass_molten': 'molten brass' as const,
	'$mat_brick': 'brick wall' as const,
	'$mat_burning_powder': 'burning powder' as const,
	'$mat_bush_seed': 'evergreen seed' as const,
	'$mat_cactus': 'grass' as const,
	'$mat_ceiling_plant_material': 'seed' as const,
	'$mat_cement': 'cement' as const,
	'$mat_cheese_static': 'cheese' as const,
	'$mat_cloud': 'cloud' as const,
	'$mat_cloud_alcohol': 'alcohol mist' as const,
	'$mat_cloud_blood': 'blood mist' as const,
	'$mat_cloud_radioactive': 'toxic mist' as const,
	'$mat_cloud_slime': 'slime mist' as const,
	'$mat_coal': 'coal' as const,
	'$mat_coal_static': 'coal vein' as const,
	'$mat_cocoon_box2d': 'cocoon' as const,
	'$mat_concrete_collapsed': 'collapsed concrete' as const,
	'$mat_concrete_sand': 'concrete' as const,
	'$mat_concrete_static': 'concrete' as const,
	'$mat_copper': 'copper' as const,
	'$mat_copper_molten': 'molten copper' as const,
	'$mat_corruption_static': 'corrupted rock' as const,
	'$mat_creepy_liquid': 'creepy liquid' as const,
	'$mat_creepy_liquid_emitter': 'brick wall' as const,
	'$mat_crystal': 'crystal' as const,
	'$mat_crystal_magic': 'crystal' as const,
	'$mat_crystal_purple': 'purple crystal' as const,
	'$mat_diamond': 'diamond' as const,
	'$mat_endslime': 'hell slime' as const,
	'$mat_endslime_blood': 'hell slime' as const,
	'$mat_endslime_static': 'hell slime' as const,
	'$mat_explosion_dirt': 'dirt' as const,
	'$mat_fire': 'fire' as const,
	'$mat_fire_blue': 'fire' as const,
	'$mat_flame': 'fire' as const,
	'$mat_fungal_gas': 'fungal gas' as const,
	'$mat_fungi': 'fungus' as const,
	'$mat_fungi_green': 'fungus' as const,
	'$mat_fungisoil': 'fungal soil' as const,
	'$mat_fungus_loose': 'fungus' as const,
	'$mat_fuse': 'bomb' as const,
	'$mat_fuse_holy': 'holy matter' as const,
	'$mat_fuse_tnt': 'tnt' as const,
	'$mat_gem_box2d': 'gem' as const,
	'$mat_gem_box2d_green': 'gem' as const,
	'$mat_gem_box2d_orange': 'gem' as const,
	'$mat_gem_box2d_pink': 'gem' as const,
	'$mat_gem_box2d_red': 'gem' as const,
	'$mat_glass': 'glass' as const,
	'$mat_glass_box2d': 'glass' as const,
	'$mat_glass_brittle': 'brittle glass' as const,
	'$mat_glass_broken_molten': 'molten glass' as const,
	'$mat_glass_molten': 'molten glass' as const,
	'$mat_glass_static': 'glass' as const,
	'$mat_glowshroom': 'glowing fungal spore' as const,
	'$mat_glowstone': 'glowing stone' as const,
	'$mat_glowstone_altar': 'glowing stone' as const,
	'$mat_glowstone_potion': 'glowing stone' as const,
	'$mat_gold': 'gold' as const,
	'$mat_gold_b2': 'gold' as const,
	'$mat_gold_box2d': 'gold' as const,
	'$mat_gold_molten': 'molten gold' as const,
	'$mat_gold_radioactive': 'toxic gold' as const,
	'$mat_gold_static': 'gold vein' as const,
	'$mat_gold_static_dark': 'vibrant gold vein' as const,
	'$mat_grass': 'grass' as const,
	'$mat_grass_loose': 'fungal matter' as const,
	'$mat_gunpowder': 'gunpowder' as const,
	'$mat_gunpowder_explosive': 'gunpowder' as const,
	'$mat_gunpowder_tnt': 'gunpowder' as const,
	'$mat_gunpowder_unstable': 'gunpowder' as const,
	'$mat_gunpowder_unstable_boss_limbs': 'slimy meat' as const,
	'$mat_honey': 'honey' as const,
	'$mat_ice': 'ice' as const,
	'$mat_ice_acid_glass': 'frozen acid' as const,
	'$mat_ice_acid_static': 'frozen acid' as const,
	'$mat_ice_b2': 'ice' as const,
	'$mat_ice_blood_static': 'frozen blood' as const,
	'$mat_ice_ceiling': 'ice' as const,
	'$mat_ice_cold_glass': 'ice' as const,
	'$mat_ice_cold_static': 'ice' as const,
	'$mat_ice_glass': 'ice' as const,
	'$mat_ice_glass_b2': 'ice' as const,
	'$mat_ice_melting_perf_killer': 'ice' as const,
	'$mat_ice_meteor_static': 'ice' as const,
	'$mat_ice_radioactive_glass': 'toxic ice' as const,
	'$mat_ice_radioactive_static': 'toxic ice' as const,
	'$mat_ice_static': 'ice' as const,
	'$mat_item_box2d': 'item' as const,
	'$mat_lava': 'lava' as const,
	'$mat_lavarock_static': 'volcanic rock' as const,
	'$mat_lavasand': 'volcanic sand' as const,
	'$mat_liquid_fire': 'fire' as const,
	'$mat_liquid_fire_weak': 'liquid fire' as const,
	'$mat_magic_liquid': 'gate-opener' as const,
	'$mat_magic_liquid_berserk': 'berserkium' as const,
	'$mat_magic_liquid_charm': 'pheromone' as const,
	'$mat_magic_liquid_hp_regeneration': 'healthium' as const,
	'$mat_magic_liquid_hp_regeneration_unstable': 'lively concoction' as const,
	'$mat_magic_liquid_invisibility': 'invisiblium' as const,
	'$mat_magic_liquid_polymorph': 'polymorphine' as const,
	'$mat_magic_liquid_random_polymorph': 'chaotic polymorphine' as const,
	'$mat_magic_liquid_teleportation': 'teleportatium' as const,
	'$mat_meat': 'meat' as const,
	'$mat_meat_slime': 'slimy meat' as const,
	'$mat_meat_slime_green': 'green slimy meat' as const,
	'$mat_meat_slime_orange': 'slimy meat' as const,
	'$mat_meat_slime_sand': 'slimy meat' as const,
	'$mat_meat_worm': 'worm meat' as const,
	'$mat_metal': 'metal' as const,
	'$mat_metal_molten': 'molten metal' as const,
	'$mat_metal_nohit': 'metal' as const,
	'$mat_metal_nohit_molten': 'molten metal' as const,
	'$mat_metal_prop': 'metal' as const,
	'$mat_metal_prop_molten': 'molten metal' as const,
	'$mat_metal_rust': 'rusted metal' as const,
	'$mat_metal_rust_barrel': 'rusted metal' as const,
	'$mat_metal_rust_barrel_rust': 'rusted metal' as const,
	'$mat_metal_rust_molten': 'molten metal' as const,
	'$mat_metal_rust_rust': 'rusted metal' as const,
	'$mat_meteorite': 'meteorite' as const,
	'$mat_meteorite_crackable': 'meteorite' as const,
	'$mat_meteorite_green': 'green meteorite' as const,
	'$mat_meteorite_static': 'meteorite' as const,
	'$mat_midas': 'draught of midas' as const,
	'$mat_midas_precursor': 'alchemic precursor' as const,
	'$mat_moss': 'moss' as const,
	'$mat_moss_rust': 'rusty moss' as const,
	'$mat_mud': 'mud' as const,
	'$mat_mushroom': 'fungal spore' as const,
	'$mat_mushroom_giant_blue': 'fungal spore' as const,
	'$mat_mushroom_giant_red': 'fungal spore' as const,
	'$mat_mushroom_seed': 'fungal spore' as const,
	'$mat_neon_tube_blood_red': 'neon tube' as const,
	'$mat_neon_tube_cyan': 'neon tube' as const,
	'$mat_neon_tube_purple': 'neon tube' as const,
	'$mat_nest_box2d': 'nest' as const,
	'$mat_nest_static': 'nest' as const,
	'$mat_oil': 'oil' as const,
	'$mat_pea_soup': 'pea soup' as const,
	'$mat_physics_throw_material_part2': 'who knows' as const,
	'$mat_plant_material': 'plant material' as const,
	'$mat_plant_material_red': 'seed' as const,
	'$mat_plant_seed': 'plant seed' as const,
	'$mat_plasma_fading': 'magical liquid' as const,
	'$mat_plasma_fading_green': 'magical liquid' as const,
	'$mat_plasma_fading_pink': 'magical liquid' as const,
	'$mat_plastic': 'plastic' as const,
	'$mat_plastic_molten': 'molten plastic' as const,
	'$mat_plastic_prop_molten': 'molten plastic' as const,
	'$mat_plastic_red': 'plastic' as const,
	'$mat_plastic_red_molten': 'molten plastic' as const,
	'$mat_poison': 'glowing liquid' as const,
	'$mat_poison_gas': 'poison gas' as const,
	'$mat_poo': 'excrement' as const,
	'$mat_potion_glass_box2d': 'glass' as const,
	'$mat_radioactive_gas': 'toxic gas' as const,
	'$mat_radioactive_gas_static': 'toxic gas' as const,
	'$mat_radioactive_liquid': 'toxic sludge' as const,
	'$mat_radioactive_liquid_fading': 'toxic sludge' as const,
	'$mat_radioactive_liquid_yellow': 'toxic sludge' as const,
	'$mat_rock_box2d': 'rock' as const,
	'$mat_rock_box2d_hard': 'rock' as const,
	'$mat_rock_box2d_nohit': 'rock' as const,
	'$mat_rock_box2d_nohit_hard': 'dense rock' as const,
	'$mat_rock_eroding': 'eroding rock' as const,
	'$mat_rock_hard': 'dense rock' as const,
	'$mat_rock_hard_border': 'extremely dense rock' as const,
	'$mat_rock_loose': 'rock' as const,
	'$mat_rock_magic_bottom': 'magic wall' as const,
	'$mat_rock_magic_gate': 'magic gate' as const,
	'$mat_rock_static': 'rock' as const,
	'$mat_rock_static_box2d': 'rock' as const,
	'$mat_rock_static_glow': 'glowing matter' as const,
	'$mat_rock_static_grey': 'grey rock' as const,
	'$mat_rock_static_intro': 'rock' as const,
	'$mat_rock_static_intro_breakable': 'rock' as const,
	'$mat_rock_static_noedge': 'rock' as const,
	'$mat_rock_static_poison': 'poisonous rock' as const,
	'$mat_rock_static_radioactive': 'toxic rock' as const,
	'$mat_rock_static_wet': 'damp rock' as const,
	'$mat_rock_vault': 'vault rock' as const,
	'$mat_rocket_particles': 'smoke' as const,
	'$mat_root': 'vine' as const,
	'$mat_rotten_meat': 'rotten meat' as const,
	'$mat_rotten_meat_radioactive': 'toxic meat' as const,
	'$mat_rust_static': 'rusted metal' as const,
	'$mat_salt': 'salt' as const,
	'$mat_sand': 'sand' as const,
	'$mat_sand_blue': 'blue sand' as const,
	'$mat_sand_herb': 'herb' as const,
	'$mat_sand_herb_vapour': 'funky vapour' as const,
	'$mat_sand_static': 'ground' as const,
	'$mat_sand_static_bright': 'granite ground' as const,
	'$mat_sand_static_rainforest': 'lush ground' as const,
	'$mat_sand_static_red': 'rusty ground' as const,
	'$mat_sandstone': 'sandstone' as const,
	'$mat_silver': 'silver' as const,
	'$mat_silver_molten': 'molten silver' as const,
	'$mat_skullrock': 'hell rock' as const,
	'$mat_slime_green': 'slime' as const,
	'$mat_slime_pink': 'slime' as const,
	'$mat_slime_static': 'slime' as const,
	'$mat_smoke': 'smoke' as const,
	'$mat_smoke_explosion': 'smoke' as const,
	'$mat_smoke_magic': 'smoke' as const,
	'$mat_smoke_static': 'smoke' as const,
	'$mat_snow': 'snow' as const,
	'$mat_snow_b2': 'snow' as const,
	'$mat_snow_static': 'packed snow' as const,
	'$mat_snowrock_static': 'frozen rock' as const,
	'$mat_sodium': 'sodium' as const,
	'$mat_sodium_unstable': 'wet sodium' as const,
	'$mat_soil': 'soil' as const,
	'$mat_soil_dead': 'barren soil' as const,
	'$mat_soil_lush': 'soil' as const,
	'$mat_spark': 'spark' as const,
	'$mat_spark_blue': 'spark' as const,
	'$mat_spark_electric': 'electric spark' as const,
	'$mat_spark_green': 'spark' as const,
	'$mat_spark_player': 'spark' as const,
	'$mat_spark_purple': 'spark' as const,
	'$mat_spark_red': 'spark' as const,
	'$mat_spark_teal': 'spark' as const,
	'$mat_spark_white': 'spark' as const,
	'$mat_spark_yellow': 'spark' as const,
	'$mat_spore': 'seed' as const,
	'$mat_steam': 'steam' as const,
	'$mat_steel': 'steel' as const,
	'$mat_steel_molten': 'molten metal' as const,
	'$mat_steel_rust': 'rusted steel' as const,
	'$mat_steel_rust_molten': 'molten steel' as const,
	'$mat_steel_sand': 'steel' as const,
	'$mat_steel_static': 'steel' as const,
	'$mat_steel_static_molten': 'molten steel' as const,
	'$mat_steel_static_strong': 'dense steel' as const,
	'$mat_steel_static_unmeltable': 'hardened steel' as const,
	'$mat_steelmoss_slanted': 'mossy steel' as const,
	'$mat_steelmoss_slanted_molten': 'molten steel' as const,
	'$mat_steelmoss_static': 'mossy steel' as const,
	'$mat_steelmoss_static_molten': 'molten steel' as const,
	'$mat_steelpipe_static': 'metal pipe' as const,
	'$mat_steelsmoke_static': 'smoking steel' as const,
	'$mat_steelsmoke_static_molten': 'molten steel' as const,
	'$mat_sulphur': 'sulphur' as const,
	'$mat_swamp': 'swamp' as const,
	'$mat_templebrick_box2d': 'brickwork' as const,
	'$mat_templebrick_moss_static': 'mossy brickwork' as const,
	'$mat_templebrick_noedge_static': 'brickwork' as const,
	'$mat_templebrick_red': 'brickwork' as const,
	'$mat_templebrick_static': 'brickwork' as const,
	'$mat_templebrick_thick_static': 'brickwork' as const,
	'$mat_templebrickdark_static': 'brickwork' as const,
	'$mat_templerock_static': 'brickwork' as const,
	'$mat_the_end': 'hell rock' as const,
	'$mat_tnt': 'tnt' as const,
	'$mat_trailer_text': 'text' as const,
	'$mat_tube_physics': 'neon tube' as const,
	'$mat_tubematerial': 'neon tube' as const,
	'$mat_urine': 'urine' as const,
	'$mat_vine': 'vine' as const,
	'$mat_water': 'Water' as const,
	'$mat_water_fading': 'Water' as const,
	'$mat_water_ice': 'chilly water' as const,
	'$mat_water_salt': 'brine' as const,
	'$mat_water_static': 'Water' as const,
	'$mat_water_swamp': 'swamp' as const,
	'$mat_water_temp': 'Water' as const,
	'$mat_waterrock': 'rock' as const,
	'$mat_wax': 'wax' as const,
	'$mat_wax_b2': 'wax' as const,
	'$mat_wax_molten': 'molten wax' as const,
	'$mat_wood': 'wood' as const,
	'$mat_wood_loose': 'wood' as const,
	'$mat_wood_player': 'wood' as const,
	'$mat_wood_player_b2': 'wood' as const,
	'$mat_wood_player_b2_vertical': 'wood' as const,
	'$mat_wood_prop': 'wood' as const,
	'$mat_wood_prop_durable': 'tough wood' as const,
	'$mat_wood_static': 'wood' as const,
	'$mat_wood_static_gas': 'pressurized wood' as const,
	'$mat_wood_static_vertical': 'wood' as const,
	'$mat_wood_static_wet': 'damp wood' as const,
	'$mat_wood_trailer': 'wood' as const,
	'$mat_wood_wall': 'wood' as const
};
