
export const liquidMaterials: string[] = [
	'water',
	'water_ice',
	'water_swamp',
	'oil',
	'alcohol',
	'swamp',
	'mud',
	'blood',
	'blood_fungi',
	'blood_worm',
	'radioactive_liquid',
	'cement',
	'acid',
	'lava',
	'urine',
	'poison',
	'magic_liquid_teleportation',
	'magic_liquid_polymorph',
	'magic_liquid_random_polymorph',
	'magic_liquid_berserk',
	'magic_liquid_charm',
	'magic_liquid_invisibility'
];

export const alchemyMaterials: string[] = [
	'sand',
	'bone',
	'soil',
	'honey',
	'slime',
	'snow',
	'rotten_meat',
	'wax',
	'gold',
	'silver',
	'copper',
	'brass',
	'diamond',
	'coal',
	'gunpowder',
	'gunpowder_explosive',
	'grass',
	'fungi'
];
